# Generated by Django 2.2.12 on 2022-06-03 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('designation', models.CharField(choices=[('SE', 'SE'), ('ASE', 'ASE'), ('SE', 'SE')], default='SE', max_length=30)),
                ('work_location', models.CharField(choices=[('BENGALURU', 'BENGALURU'), ('HYDERABAD', 'HYDERABAD')], default='BENGARULU', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('STORY', 'STORY'), ('POST', 'POST')], default='POST', max_length=30)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(null=True, upload_to='static/', verbose_name='Photo')),
                ('video', models.FileField(null=True, upload_to='static/', verbose_name='Video')),
                ('description', models.TextField(max_length=500, null=True)),
                ('tags', models.CharField(max_length=50, null=True)),
                ('links', models.URLField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='userapp.Posts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_user', to=settings.AUTH_USER_MODEL)),
                ('postid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_feedbackid', to='userapp.Posts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='userapp.Posts')),
            ],
        ),
    ]
