# Generated by Django 2.2.12 on 2022-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20220606_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('STORY', 'STORY'), ('POST', 'POST')], max_length=30),
        ),
    ]
