# Generated by Django 2.2.12 on 2022-06-06 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20220606_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO')], default='PHOTO', max_length=20)),
                ('event_file', models.FileField(null=True, upload_to='static/', verbose_name='event_images')),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='userapp.Events')),
            ],
        ),
    ]
