# Generated by Django 2.2.12 on 2022-06-07 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_eventphotos_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphotos',
            old_name='file_type',
            new_name='eventfile_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='postid',
        ),
        migrations.AddField(
            model_name='feedback',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_feedbackid', to='userapp.Events'),
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video'), ('Text', 'Text')], default='Photo', max_length=20)),
                ('post_file', models.FileField(null=True, upload_to='static/', verbose_name='post_images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='userapp.Posts')),
            ],
        ),
    ]
